#Volumes are different on windows and linux
#From browser use localhost
#From a docker container use the another docker container's name

version: '3.4'
services:
 RabbitMQ:
  image: rabbitmq:management
  container_name: RabbitMQ
  hostname: pubsub-queue
  volumes:
   - ./.containers/RabbitMQ/data/:/var/lib/rabbitmq
   - ./.containers/RabbitMQ/log/:/var/log/rabbitmq
  ports:
   - 5672:5672
   - 15672:15672
  environment:
   RABBITMQ_DEFAULT_USER: guest
   RABBITMQ_DEFAULT_PASS: guest
 publisherApp:
  image: balintsedlakoneidentity/dockerdemo_publisher
  container_name: publisher-pull
  build:
   context: .
   dockerfile: ./docker/Publisher/Dockerfile
  environment:
   RabbitMQ__Host: "RabbitMQ"
   RabbitMQ__Port: "5672"
   RabbitMQ__Username: "guest"
   RabbitMQ__Password: "guest"
   CORS_ALLOWED_ORIGINS: http://localhost:3001
  ports:
   - "5000:8080"   
 subscriberApp:
  image: balintsedlakoneidentity/dockerdemo_subscriber
  container_name: subscriber-pull
  build:
   context: .
   dockerfile: ./docker/Subscriber/Dockerfile
  environment:
   RabbitMQ__Host: "RabbitMQ"
   RabbitMQ__Port: "5672"
   RabbitMQ__Username: "guest"
   RabbitMQ__Password: "guest"
   CORS_ALLOWED_ORIGINS: http://localhost:5672,http://rabbitmq:5672
  ports:
   - "5001:8080"   
 frontend:
  image: balintsedlakoneidentity/dockerdemo_frontend
  container_name: frontend-pull
  build:
   context: .
   target: production
   dockerfile: ./docker/Frontend/Dockerfile
  # volumes:
  #  - ./frontend/src:/app/src
  ports:
   - "3001:80"
  environment:
   REACT_APP_PUBLISHER_URL: http://localhost:5000